/**
 * Seed Data - Sample Books for Digital Catalog
 */

import {
  DigitalContentMetadata,
  DigitalFormat,
  DRMType,
} from '@/types/digital-content';

export const sampleBooks: DigitalContentMetadata[] = [
  {
    contentId: 'ebook-001',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    formatType: DigitalFormat.EPUB,
    drmType: DRMType.NONE,
    fileSizeMB: 2.5,
    isbn: '9780743273565',
    publisher: 'Scribner',
    publicationDate: new Date('1925-04-10'),
    description: 'A classic American novel set in the Jazz Age, exploring themes of decadence, idealism, and social upheaval.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780743273565-M.jpg',
    totalCopies: 5,
    availableCopies: 3,
    pageCount: 180,
    genre: 'Fiction',
    language: 'en',
  },
  {
    contentId: 'ebook-002',
    title: '1984',
    author: 'George Orwell',
    formatType: DigitalFormat.PDF,
    drmType: DRMType.ADOBE,
    fileSizeMB: 3.2,
    isbn: '9780451524935',
    publisher: 'Signet Classic',
    publicationDate: new Date('1949-06-08'),
    description: 'A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780451524935-M.jpg',
    totalCopies: 10,
    availableCopies: 7,
    pageCount: 328,
    genre: 'Science Fiction',
    language: 'en',
  },
  {
    contentId: 'ebook-003',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    formatType: DigitalFormat.EPUB,
    drmType: DRMType.NONE,
    fileSizeMB: 2.8,
    isbn: '9780061120084',
    publisher: 'Harper Perennial',
    publicationDate: new Date('1960-07-11'),
    description: 'A gripping tale of racial injustice and childhood innocence in the American South.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780061120084-M.jpg',
    totalCopies: 8,
    availableCopies: 8,
    pageCount: 324,
    genre: 'Fiction',
    language: 'en',
  },
  {
    contentId: 'ebook-004',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    formatType: DigitalFormat.EPUB,
    drmType: DRMType.NONE,
    fileSizeMB: 1.9,
    isbn: '9780141439518',
    publisher: 'Penguin Classics',
    publicationDate: new Date('1813-01-28'),
    description: 'A romantic novel of manners that critiques the British landed gentry at the end of the 18th century.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780141439518-M.jpg',
    totalCopies: 6,
    availableCopies: 4,
    pageCount: 432,
    genre: 'Romance',
    language: 'en',
  },
  {
    contentId: 'ebook-005',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    formatType: DigitalFormat.EPUB,
    drmType: DRMType.CUSTOM,
    fileSizeMB: 4.1,
    isbn: '9780547928227',
    publisher: 'Houghton Mifflin',
    publicationDate: new Date('1937-09-21'),
    description: 'A fantasy adventure about Bilbo Baggins\' journey to reclaim a treasure guarded by a dragon.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780547928227-M.jpg',
    totalCopies: 12,
    availableCopies: 9,
    pageCount: 310,
    genre: 'Fantasy',
    language: 'en',
  },
  {
    contentId: 'audiobook-001',
    title: 'Atomic Habits',
    author: 'James Clear',
    formatType: DigitalFormat.AUDIOBOOK,
    drmType: DRMType.OVERDRIVE,
    fileSizeMB: 125.5,
    isbn: '9780735211292',
    publisher: 'Penguin Audio',
    publicationDate: new Date('2018-10-16'),
    description: 'An easy and proven way to build good habits and break bad ones.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780735211292-M.jpg',
    totalCopies: 3,
    availableCopies: 2,
    genre: 'Self-Help',
    language: 'en',
    duration: 317,
    narrator: 'James Clear',
  },
  {
    contentId: 'ebook-006',
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    formatType: DigitalFormat.PDF,
    drmType: DRMType.ADOBE,
    fileSizeMB: 2.1,
    isbn: '9780316769488',
    publisher: 'Little, Brown and Company',
    publicationDate: new Date('1951-07-16'),
    description: 'A story about teenage rebellion and alienation narrated by Holden Caulfield.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780316769488-M.jpg',
    totalCopies: 7,
    availableCopies: 5,
    pageCount: 277,
    genre: 'Fiction',
    language: 'en',
  },
  {
    contentId: 'ebook-007',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    formatType: DigitalFormat.EPUB,
    drmType: DRMType.ADOBE,
    fileSizeMB: 5.3,
    isbn: '9780062316097',
    publisher: 'Harper',
    publicationDate: new Date('2015-02-10'),
    description: 'An exploration of the history and impact of Homo sapiens on the world.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780062316097-M.jpg',
    totalCopies: 15,
    availableCopies: 11,
    pageCount: 443,
    genre: 'Non-Fiction',
    language: 'en',
  },
  {
    contentId: 'ebook-008',
    title: 'Harry Potter and the Sorcerer\'s Stone',
    author: 'J.K. Rowling',
    formatType: DigitalFormat.EPUB,
    drmType: DRMType.CUSTOM,
    fileSizeMB: 3.7,
    isbn: '9780439708180',
    publisher: 'Scholastic',
    publicationDate: new Date('1998-09-01'),
    description: 'A young wizard discovers his magical heritage on his 11th birthday.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780439708180-M.jpg',
    totalCopies: 20,
    availableCopies: 0,
    pageCount: 309,
    genre: 'Fantasy',
    language: 'en',
  },
  {
    contentId: 'audiobook-002',
    title: 'Becoming',
    author: 'Michelle Obama',
    formatType: DigitalFormat.AUDIOBOOK,
    drmType: DRMType.OVERDRIVE,
    fileSizeMB: 532.8,
    isbn: '9781524763138',
    publisher: 'Random House Audio',
    publicationDate: new Date('2018-11-13'),
    description: 'The memoir of former First Lady of the United States Michelle Obama.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781524763138-M.jpg',
    totalCopies: 5,
    availableCopies: 1,
    genre: 'Biography',
    language: 'en',
    duration: 1140,
    narrator: 'Michelle Obama',
  },
  {
    contentId: 'ebook-009',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    formatType: DigitalFormat.EPUB,
    drmType: DRMType.NONE,
    fileSizeMB: 1.8,
    isbn: '9780061122415',
    publisher: 'HarperOne',
    publicationDate: new Date('1988-01-01'),
    description: 'A philosophical novel about a young shepherd\'s journey to find treasure.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780061122415-M.jpg',
    totalCopies: 10,
    availableCopies: 6,
    pageCount: 208,
    genre: 'Fiction',
    language: 'en',
  },
  {
    contentId: 'ebook-010',
    title: 'Educated',
    author: 'Tara Westover',
    formatType: DigitalFormat.PDF,
    drmType: DRMType.ADOBE,
    fileSizeMB: 4.5,
    isbn: '9780399590504',
    publisher: 'Random House',
    publicationDate: new Date('2018-02-20'),
    description: 'A memoir about a young woman who leaves her survivalist family to pursue education.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780399590504-M.jpg',
    totalCopies: 8,
    availableCopies: 3,
    pageCount: 334,
    genre: 'Memoir',
    language: 'en',
  },
];
